### ISSUE TITLE
Animometer.dynamicOffsets seems to have no effect at all in the demo

### ISSUE THREAD

**Issue by tlecoz** [webgpu/webgpu-samples#213]
Hello

I'm studying the code of the Animometer demo and even if I think I understand the main idea behind it, I'm surprise to observ that the "dynamicOffsets" settings has no impact at all on the rendering framerate. 
Is it normal ?

If yes, what should we conclude about it ? 
In what kind of scenario is it better to use (or not to use) dynamicOffsets ? 

This is the first time I see a demo that uses a UniformBuffer to store so much datas instead of using a VertexBuffer. 
Is it a good practice to store a minimal geometry inside a VertexBuffer and everything else inside a uniformBuffer or is this demo just an example to show that it's possible ?

**Comment by austinEng** [comment]
> This is the first time I see a demo that uses a UniformBuffer to store so much datas instead of using a VertexBuffer.

Animometer is a a port of the MotionMark animometer benchmark which is a synthetic workload meant to stress sending a very high number of commands to the GPU. It would definitely be recommended in a real application to put this data in a vertex buffer, but the benchmark intended to stress bindData, draw, bindData, draw, ..., etc. over and over again.

The expected difference with dynamicOffsets is that there's theoretically a CPU performance difference between setting a new bind group for every draw, and setting the same one at a different offset. There should also be some memory improvements because with dynamic offsets, you only need one bind group instead of many. In this synthetic benchmark, however, you're right - there isn't much of a difference.
