### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by Tsuki1mega** [webgpu/webgpu-samples#288]
I would like to add a keyboard control in the cornell, to control the position of the light source, but when I use the code of document.addEventListener('keydown', this.KeydownHandler) to read the keyboard, the result shows me ReferenceError: document is not defined. I don not why this happened, can you help me ?

**Comment by kainino0x** [comment]
I don't know much about this but it has to do with the way the webpage framework works. Your `document.addEventListener` call is happening in the server, instead of in the webpage, I think due to [Server-Side Rendering](https://nextjs.org/docs/pages/building-your-application/rendering/server-side-rendering).

Basically make sure the code is happening in the right place. For example in main.ts, it cannot be at the top-level of the file, it must be inside `init()` or a function called from `init()`.

**Comment by Tsuki1mega** [comment]
> I don't know much about this but it has to do with the way the webpage framework works. Your `document.addEventListener` call is happening in the server, instead of in the webpage, I think due to [Server-Side Rendering](https://nextjs.org/docs/pages/building-your-application/rendering/server-side-rendering).
> 
> Basically make sure the code is happening in the right place. For example in main.ts, it cannot be at the top-level of the file, it must be inside `init()` or a function called from `init()`.

yeah, I put  document.addEventListener inside init() but it still not works.

**Comment by austinEng** [comment]
I think something like:
```
useEffect(() => {
  if (typeof window !== "undefined") {
    document.addEventListener(...)
  }
});
```
should work
